CREATE TABLE billing_purchase_order (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_no VARCHAR(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    plan_version_id BIGINT UNSIGNED NOT NULL,
    plan_code VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    plan_name VARCHAR(120) NOT NULL,
    amount_minor BIGINT UNSIGNED NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING_PAYMENT',
    idempotency_key VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    expires_at DATETIME(6) NOT NULL,
    paid_at DATETIME(6) NULL,
    fulfilled_at DATETIME(6) NULL,
    subscription_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_order_no (order_no),
    UNIQUE KEY uk_purchase_order_user_idempotency (user_id, idempotency_key),
    KEY idx_purchase_order_user_created (user_id, created_at, id),
    KEY idx_purchase_order_status_expiry (status, expires_at),
    KEY idx_purchase_order_plan_version (plan_version_id),
    CONSTRAINT fk_purchase_order_plan_version FOREIGN KEY (plan_version_id) REFERENCES billing_plan_version (id),
    CONSTRAINT fk_purchase_order_subscription FOREIGN KEY (subscription_id) REFERENCES billing_subscription (id),
    CONSTRAINT chk_purchase_order_currency CHECK (CHAR_LENGTH(currency) = 3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE billing_payment_attempt (
    id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    order_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider VARCHAR(24) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    provider_payment_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    amount_minor BIGINT UNSIGNED NOT NULL,
    currency CHAR(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(24) NOT NULL,
    failure_reason VARCHAR(255) NULL,
    paid_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_payment_provider_reference (provider, provider_payment_id),
    KEY idx_payment_order_created (order_id, created_at),
    CONSTRAINT fk_payment_attempt_order FOREIGN KEY (order_id) REFERENCES billing_purchase_order (id),
    CONSTRAINT chk_payment_attempt_currency CHECK (CHAR_LENGTH(currency) = 3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
