spring:
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  profiles:
    default: dev
  application:
    name: lumora-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${LUMORA_NACOS_ADDR:127.0.0.1:8848}

server:
  port: ${LUMORA_GATEWAY_PORT:46100}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,sentinel

lumora:
  security:
    internal-token: ${LUMORA_INTERNAL_TOKEN}
  auth:
    jwt:
      secret: ${LUMORA_JWT_SECRET}
