spring:
  application:
    name: lumora-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${LUMORA_NACOS_ADDR:127.0.0.1:8848}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

server:
  port: ${LUMORA_GATEWAY_PORT:46100}

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
